/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Project1 = string;
export type Scene = string;
export type Id = string;
export type Preset = string;
export type Spawn = string;
export type Characters = Character[];
export type Id1 = string;
export type Start = number;
export type End = number;
export type Camera = string;
export type Id2 = string;
export type Start1 = number;
export type End1 = number;
export type Type = "walk_to";
export type Character1 = string;
export type Target = string;
export type Emotion = "neutral" | "joy" | "angry" | "sorrow" | "fun";
/**
 * Gait flavor applied to walk_to. The executor maps these to NLA-strip
 * speed multipliers on top of the standard walk_in_place clip — no
 * per-style FBX required. Sneak is the slowest, run the fastest.
 */
export type WalkStyle = "walk" | "run" | "jog" | "sneak" | "march" | "limp";
export type Id3 = string;
export type Start2 = number;
export type End2 = number;
export type Type1 = "idle";
export type Character2 = string;
/**
 * Emotional/postural flavor applied to idle. Currently informational —
 * the LLM picks a style and downstream tools can branch on it, but the
 * executor doesn't yet have per-style idle clips.
 */
export type IdleStyle = "neutral" | "tired" | "alert" | "confident" | "bored" | "nervous";
export type Id4 = string;
export type Start3 = number;
export type End3 = number;
export type Type2 = "turn_to";
export type Character3 = string;
export type Target1 = string;
export type Id5 = string;
export type Start4 = number;
export type End4 = number;
export type Type3 = "look_at";
export type Character4 = string;
export type Target2 = string;
export type Id6 = string;
export type Start5 = number;
export type End5 = number;
export type Type4 = "point_at";
export type Character5 = string;
export type Target3 = string;
/**
 * Body parts this point gesture drives. Defaults to [right_arm]. Set to override (e.g. left_arm) when the character should point with a different limb.
 */
export type BoneMask = BodyPart[] | null;
/**
 * Coarse body regions used by the optional `bone_mask` field on gestures.
 *
 * A gesture's bone_mask declares which limbs the action drives. Listeners
 * use this to reason about layering: a `wave` (right_arm only) can run
 * concurrently with a `walk_to` (full-body locomotion) without clobbering
 * the legs, while two right_arm actions at the same time conflict.
 *
 * Values are intentionally coarse (one per limb / region) so the LLM can
 * pick them by name without needing to know the underlying Mixamo bone
 * naming. The executor maps each part to its bones internally.
 */
export type BodyPart = "head" | "spine" | "left_arm" | "right_arm" | "left_leg" | "right_leg" | "face";
export type Id7 = string;
export type Start6 = number;
export type End6 = number;
export type Type5 = "sit";
export type Character6 = string;
export type Id8 = string;
export type Start7 = number;
export type End7 = number;
export type Type6 = "stand";
export type Character7 = string;
export type Id9 = string;
export type Start8 = number;
export type End8 = number;
export type Type7 = "smile";
export type Character8 = string;
export type Id10 = string;
export type Start9 = number;
export type End9 = number;
export type Type8 = "frown";
export type Character9 = string;
export type Id11 = string;
export type Start10 = number;
export type End10 = number;
export type Type9 = "blink";
export type Character10 = string;
export type Id12 = string;
export type Start11 = number;
export type End11 = number;
export type Type10 = "talk";
export type Character11 = string;
export type Text = string;
export type LookAt = string | null;
export type Gesture = string | null;
export type Id13 = string;
export type Start12 = number;
export type End12 = number;
export type Type11 = "nod";
export type Character12 = string;
/**
 * Body parts this nod drives. Defaults to [head].
 */
export type BoneMask1 = BodyPart[] | null;
export type Id14 = string;
export type Start13 = number;
export type End13 = number;
export type Type12 = "shake_head";
export type Character13 = string;
/**
 * Body parts this head shake drives. Defaults to [head].
 */
export type BoneMask2 = BodyPart[] | null;
export type Id15 = string;
export type Start14 = number;
export type End14 = number;
export type Type13 = "wave";
export type Character14 = string;
export type Target4 = string | null;
/**
 * Body parts this wave drives. Defaults to [right_arm]. Override to [left_arm] for a left-handed wave.
 */
export type BoneMask3 = BodyPart[] | null;
export type Id16 = string;
export type Start15 = number;
export type End15 = number;
export type Type14 = "camera_cut";
export type Camera1 = string;
export type Id17 = string;
export type Start16 = number;
export type End16 = number;
export type Type15 = "camera_dolly";
export type FromCamera = string;
export type ToCamera = string;
export type Id18 = string;
export type Start17 = number;
export type End17 = number;
export type Type16 = "track_subject";
export type Character15 = string;
export type Id19 = string;
export type Start18 = number;
export type End18 = number;
export type Type17 = "two_shot";
export type A = string;
export type B = string;
export type Id20 = string;
export type Start19 = number;
export type End19 = number;
export type Type18 = "over_shoulder";
export type A1 = string;
export type B1 = string;
export type Id21 = string;
export type Start20 = number;
export type End20 = number;
export type Type19 = "orbit";
export type Target5 = string;
export type Degrees = number;
export type Id22 = string;
export type Start21 = number;
export type End21 = number;
export type Type20 = "set_lighting";
export type Preset1 = string;
export type Actions = (
  | WalkToAction
  | IdleAction
  | TurnToAction
  | LookAtAction
  | PointAtAction
  | SitAction
  | StandAction
  | SmileAction
  | FrownAction
  | BlinkAction
  | TalkAction
  | NodAction
  | ShakeHeadAction
  | WaveAction
  | CameraCutAction
  | CameraDollyAction
  | TrackSubjectAction
  | TwoShotAction
  | OverShoulderAction
  | OrbitAction
  | SetLightingAction
)[];
export type Shots = Shot[];

export interface Project {
  project: Project1;
  scene: Scene;
  characters: Characters;
  shots: Shots;
  [k: string]: unknown;
}
export interface Character {
  id: Id;
  preset: Preset;
  spawn: Spawn;
  [k: string]: unknown;
}
export interface Shot {
  id: Id1;
  start: Start;
  end: End;
  camera: Camera;
  actions: Actions;
  [k: string]: unknown;
}
export interface WalkToAction {
  id: Id2;
  start: Start1;
  end: End1;
  type?: Type;
  character: Character1;
  target: Target;
  emotion?: Emotion | null;
  style?: WalkStyle | null;
  [k: string]: unknown;
}
export interface IdleAction {
  id: Id3;
  start: Start2;
  end: End2;
  type?: Type1;
  character: Character2;
  emotion?: Emotion | null;
  style?: IdleStyle | null;
  [k: string]: unknown;
}
export interface TurnToAction {
  id: Id4;
  start: Start3;
  end: End3;
  type?: Type2;
  character: Character3;
  target: Target1;
  [k: string]: unknown;
}
export interface LookAtAction {
  id: Id5;
  start: Start4;
  end: End4;
  type?: Type3;
  character: Character4;
  target: Target2;
  [k: string]: unknown;
}
export interface PointAtAction {
  id: Id6;
  start: Start5;
  end: End5;
  type?: Type4;
  character: Character5;
  target: Target3;
  bone_mask?: BoneMask;
  [k: string]: unknown;
}
export interface SitAction {
  id: Id7;
  start: Start6;
  end: End6;
  type?: Type5;
  character: Character6;
  [k: string]: unknown;
}
export interface StandAction {
  id: Id8;
  start: Start7;
  end: End7;
  type?: Type6;
  character: Character7;
  [k: string]: unknown;
}
export interface SmileAction {
  id: Id9;
  start: Start8;
  end: End8;
  type?: Type7;
  character: Character8;
  [k: string]: unknown;
}
export interface FrownAction {
  id: Id10;
  start: Start9;
  end: End9;
  type?: Type8;
  character: Character9;
  [k: string]: unknown;
}
export interface BlinkAction {
  id: Id11;
  start: Start10;
  end: End10;
  type?: Type9;
  character: Character10;
  [k: string]: unknown;
}
export interface TalkAction {
  id: Id12;
  start: Start11;
  end: End11;
  type?: Type10;
  character: Character11;
  text: Text;
  emotion?: Emotion | null;
  look_at?: LookAt;
  gesture?: Gesture;
  [k: string]: unknown;
}
/**
 * Vertical head-bone pitch oscillation (yes-nod).
 *
 * Touches the head bone only — safe to layer over walk_to / idle.
 */
export interface NodAction {
  id: Id13;
  start: Start12;
  end: End12;
  type?: Type11;
  character: Character12;
  bone_mask?: BoneMask1;
  [k: string]: unknown;
}
/**
 * Horizontal head-bone yaw oscillation (no-shake).
 *
 * Touches the head bone only — safe to layer over walk_to / idle.
 */
export interface ShakeHeadAction {
  id: Id14;
  start: Start13;
  end: End13;
  type?: Type12;
  character: Character13;
  bone_mask?: BoneMask2;
  [k: string]: unknown;
}
/**
 * Right-arm wave — raises and oscillates the forearm.
 *
 * Touches the right-arm bones only — safe to layer over walk_to / idle
 * (whose right-arm motion comes from the FBX cycle, which the wave
 * keyframes override at the pose level).
 */
export interface WaveAction {
  id: Id15;
  start: Start14;
  end: End14;
  type?: Type13;
  character: Character14;
  target?: Target4;
  bone_mask?: BoneMask3;
  [k: string]: unknown;
}
export interface CameraCutAction {
  id: Id16;
  start: Start15;
  end: End15;
  type?: Type14;
  camera: Camera1;
  [k: string]: unknown;
}
export interface CameraDollyAction {
  id: Id17;
  start: Start16;
  end: End16;
  type?: Type15;
  from_camera: FromCamera;
  to_camera: ToCamera;
  [k: string]: unknown;
}
/**
 * Active camera follows a character handle for the action's duration.
 *
 * The camera's position is animated from a behind-and-above offset relative
 * to the character at start_frame to the same offset at end_frame. If the
 * character walks during the window, the camera tracks them.
 */
export interface TrackSubjectAction {
  id: Id18;
  start: Start17;
  end: End17;
  type?: Type16;
  character: Character15;
  [k: string]: unknown;
}
/**
 * Active camera repositions to frame both `a` and `b` for the duration.
 *
 * Camera is placed perpendicular to the line A↔B, looking at the midpoint,
 * at a distance proportional to their separation so both fit in frame.
 */
export interface TwoShotAction {
  id: Id19;
  start: Start18;
  end: End18;
  type?: Type17;
  a: A;
  b: B;
  [k: string]: unknown;
}
/**
 * Over-the-shoulder camera: positioned behind `a`, looking at `b`.
 *
 * Classic dialogue framing — the viewer sees the side of A's shoulder/head
 * on one edge of the frame with B in conversation across the cut. The
 * camera sits at a fixed offset behind A (along the -direction from A to B)
 * and looks at B's upper body.
 */
export interface OverShoulderAction {
  id: Id20;
  start: Start19;
  end: End19;
  type?: Type18;
  a: A1;
  b: B1;
  [k: string]: unknown;
}
/**
 * Active camera circles a target by `degrees` over the action duration.
 *
 * Positive degrees rotate counterclockwise (when viewed from above).
 * Target is either a character handle or a scene spawn-point name.
 */
export interface OrbitAction {
  id: Id21;
  start: Start20;
  end: End20;
  type?: Type19;
  target: Target5;
  degrees?: Degrees;
  [k: string]: unknown;
}
export interface SetLightingAction {
  id: Id22;
  start: Start21;
  end: End21;
  type?: Type20;
  preset: Preset1;
  [k: string]: unknown;
}
