/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Project1 = string;
export type Scene = string;
export type Id = string;
export type Preset = string;
export type Spawn = string;
export type Characters = Character[];
export type Id1 = string;
export type Start = number;
export type End = number;
export type Camera = string;
export type Id2 = string;
export type Start1 = number;
export type End1 = number;
export type Type = "walk_to";
export type Character1 = string;
export type Target = string;
export type Emotion = "neutral" | "joy" | "angry" | "sorrow" | "fun";
export type Id3 = string;
export type Start2 = number;
export type End2 = number;
export type Type1 = "idle";
export type Character2 = string;
export type Id4 = string;
export type Start3 = number;
export type End3 = number;
export type Type2 = "turn_to";
export type Character3 = string;
export type Target1 = string;
export type Id5 = string;
export type Start4 = number;
export type End4 = number;
export type Type3 = "look_at";
export type Character4 = string;
export type Target2 = string;
export type Id6 = string;
export type Start5 = number;
export type End5 = number;
export type Type4 = "point_at";
export type Character5 = string;
export type Target3 = string;
export type Id7 = string;
export type Start6 = number;
export type End6 = number;
export type Type5 = "sit";
export type Character6 = string;
export type Id8 = string;
export type Start7 = number;
export type End7 = number;
export type Type6 = "stand";
export type Character7 = string;
export type Id9 = string;
export type Start8 = number;
export type End8 = number;
export type Type7 = "smile";
export type Character8 = string;
export type Id10 = string;
export type Start9 = number;
export type End9 = number;
export type Type8 = "frown";
export type Character9 = string;
export type Id11 = string;
export type Start10 = number;
export type End10 = number;
export type Type9 = "blink";
export type Character10 = string;
export type Id12 = string;
export type Start11 = number;
export type End11 = number;
export type Type10 = "talk";
export type Character11 = string;
export type Text = string;
export type LookAt = string | null;
export type Gesture = string | null;
export type Id13 = string;
export type Start12 = number;
export type End12 = number;
export type Type11 = "camera_cut";
export type Camera1 = string;
export type Id14 = string;
export type Start13 = number;
export type End13 = number;
export type Type12 = "camera_dolly";
export type FromCamera = string;
export type ToCamera = string;
export type Id15 = string;
export type Start14 = number;
export type End14 = number;
export type Type13 = "set_lighting";
export type Preset1 = string;
export type Actions = (
  | WalkToAction
  | IdleAction
  | TurnToAction
  | LookAtAction
  | PointAtAction
  | SitAction
  | StandAction
  | SmileAction
  | FrownAction
  | BlinkAction
  | TalkAction
  | CameraCutAction
  | CameraDollyAction
  | SetLightingAction
)[];
export type Shots = Shot[];

export interface Project {
  project: Project1;
  scene: Scene;
  characters: Characters;
  shots: Shots;
  [k: string]: unknown;
}
export interface Character {
  id: Id;
  preset: Preset;
  spawn: Spawn;
  [k: string]: unknown;
}
export interface Shot {
  id: Id1;
  start: Start;
  end: End;
  camera: Camera;
  actions: Actions;
  [k: string]: unknown;
}
export interface WalkToAction {
  id: Id2;
  start: Start1;
  end: End1;
  type?: Type;
  character: Character1;
  target: Target;
  emotion?: Emotion | null;
  [k: string]: unknown;
}
export interface IdleAction {
  id: Id3;
  start: Start2;
  end: End2;
  type?: Type1;
  character: Character2;
  emotion?: Emotion | null;
  [k: string]: unknown;
}
export interface TurnToAction {
  id: Id4;
  start: Start3;
  end: End3;
  type?: Type2;
  character: Character3;
  target: Target1;
  [k: string]: unknown;
}
export interface LookAtAction {
  id: Id5;
  start: Start4;
  end: End4;
  type?: Type3;
  character: Character4;
  target: Target2;
  [k: string]: unknown;
}
export interface PointAtAction {
  id: Id6;
  start: Start5;
  end: End5;
  type?: Type4;
  character: Character5;
  target: Target3;
  [k: string]: unknown;
}
export interface SitAction {
  id: Id7;
  start: Start6;
  end: End6;
  type?: Type5;
  character: Character6;
  [k: string]: unknown;
}
export interface StandAction {
  id: Id8;
  start: Start7;
  end: End7;
  type?: Type6;
  character: Character7;
  [k: string]: unknown;
}
export interface SmileAction {
  id: Id9;
  start: Start8;
  end: End8;
  type?: Type7;
  character: Character8;
  [k: string]: unknown;
}
export interface FrownAction {
  id: Id10;
  start: Start9;
  end: End9;
  type?: Type8;
  character: Character9;
  [k: string]: unknown;
}
export interface BlinkAction {
  id: Id11;
  start: Start10;
  end: End10;
  type?: Type9;
  character: Character10;
  [k: string]: unknown;
}
export interface TalkAction {
  id: Id12;
  start: Start11;
  end: End11;
  type?: Type10;
  character: Character11;
  text: Text;
  emotion?: Emotion | null;
  look_at?: LookAt;
  gesture?: Gesture;
  [k: string]: unknown;
}
export interface CameraCutAction {
  id: Id13;
  start: Start12;
  end: End12;
  type?: Type11;
  camera: Camera1;
  [k: string]: unknown;
}
export interface CameraDollyAction {
  id: Id14;
  start: Start13;
  end: End13;
  type?: Type12;
  from_camera: FromCamera;
  to_camera: ToCamera;
  [k: string]: unknown;
}
export interface SetLightingAction {
  id: Id15;
  start: Start14;
  end: End14;
  type?: Type13;
  preset: Preset1;
  [k: string]: unknown;
}
